[Icon Theme]
Name=ElevenTwilightColoredToolbars
Comment=Colored Windows 11 style toolbar icons, on top of ElevenTwilight
Version=1.2
Inherits=ElevenTwilight,breeze,Adwaita,hicolor
Example=document-save

FollowsColorScheme=true
KDE-Extensions=.svg
DisplayDepth=32

DesktopDefault=32
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=16
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=16
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=24
PanelSizes=16,22,24,32,48,64
DialogDefault=24
DialogSizes=16,22,24,32,48,64

# Directory list
Directories=16/actions,22/actions,24/actions,32/actions,scalable/actions,16/apps,16/places,22/apps,22/places,24/apps,24/places,32/apps,32/places,48/apps,48/places,64/apps,64/places,scalable/places,symbolic/actions,symbolic/apps,symbolic/places,symbolic/status,symbolic/ui

[16/actions]
Context=Actions
Size=16
Type=Fixed

[22/actions]
Context=Actions
Size=22
Type=Fixed

[24/actions]
Context=Actions
Size=24
Type=Fixed

[32/actions]
Context=Actions
Size=32
Type=Fixed

[scalable/actions]
Context=Actions
Size=48
Type=Scalable
MinSize=33
MaxSize=512

[16/apps]
Context=Applications
Size=16
Type=Fixed

[16/places]
Context=Places
Size=16
Type=Fixed

[22/apps]
Context=Applications
Size=22
Type=Fixed

[22/places]
Context=Places
Size=22
Type=Fixed

[24/apps]
Context=Applications
Size=24
Type=Fixed

[24/places]
Context=Places
Size=24
Type=Fixed

[32/apps]
Context=Applications
Size=32
Type=Fixed

[32/places]
Context=Places
Size=32
Type=Fixed

[48/apps]
Context=Applications
Size=48
Type=Fixed

[48/places]
Context=Places
Size=48
Type=Fixed

[64/apps]
Context=Applications
Size=64
MinSize=64
MaxSize=256
Type=Scalable

[64/places]
Context=Places
Size=64
MinSize=64
MaxSize=256
Type=Scalable

[scalable/places]
Context=Places
Size=64
MinSize=64
MaxSize=256
Type=Scalable

[symbolic/actions]
Context=Actions
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/apps]
Context=Applications
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/places]
Context=Places
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/status]
Context=Status
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/ui]
Context=UI
Size=16
MinSize=16
MaxSize=512
Type=Scalable
